name: PHP Linting

on:
  pull_request:
    branches: [ "main" ]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Running Pint
        uses: aglipanci/laravel-pint-action@2.3.0
        with:
          configPath: "pint.json"
          useComposer: true
          onlyDirty: true
          testMode: true
